### ISSUE TITLE
Typos in Light Wallet console greeting.

### ISSUE THREAD

**Issue by E4GLY** [lbtcio/lbtc-lightwallet-client#10]
If you view the console window in the light wallet, the default greeting is:
"**Wecome** on board!
Website:lightningbitcoin.io
Twitter/Telegram:LightningBTC
**Wish** you a **greate** journey." 

.....which has a couple of typos, it should be:
"Welcome on board!
Website:lightningbitcoin.io
Twitter/Telegram:LightningBTC
We wish you a great journey.
"

Would look more professional/ less flaky to native English speakers without the typos ;)

Regards

**Comment by sunshineben** [comment]
thanks for you concern, this issue has been corrected ! we will merge this issue into v1.0 release !
